### ISSUE TITLE
Time covers bubbles when underwater

### ISSUE THREAD

**Issue by Polar-Onyx** [BTW-Community/Random-Things-Addon#1]
Can be quite annoying to mine clay when I can't see how much bubbles are left.
I would like an option to hide the timer or just move it to the top right of the screen.

**Comment by SleepiiDragon** [comment]
working on fixing this right now, i wouldnt have much clue as to how to move it to the top right though

**Comment by SleepiiDragon** [comment]
oh yeah i forgot i fixed this, yeah, though as of writing this comment the latest full release of btw itself has this issue.
